name: "Fenix V24 integration"
description: ""
version: "1.0.0"
slug: "rb_ha_fenix24"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  email: ""
  password: ""
  smarthome_id: ""
schema:
  email: str
  password: str
  smarthome_id: str
